#!/bin/sh

# Usage function
function usage() {
  cat >&2 <<EOF
${SH_FILE} is used to compile official OpenSBI firmware

Usage: ${SH_FILE} -b board [-c] [-h] [-d] [-s dir]

Where:
  -b    name of the board to configure
  -c    copy firmware file
  -d    compile firmware in debug mode
  -s	OpenSBI source directory
  -h    this help page

Currently supported boards are: beaglev/starlight, visionfive and visionfive2/visionfive2-sdk
EOF
  exit 0
}

# Error function
function error() {
  echo -e "$@" >&2
  exit 1
}

# Copy/Check function
function copy() {
  typeset -r FILE=$1
  typeset -r DEST=$2

  cp ${FILE} ${DEST} >/dev/null 2>&1 \
    || error "Error while copying file ${FILE} to ${DEST}!"
}

# Variable(s)
typeset -r SH_FILE=${0##*/}
typeset -r TMPFS=/dev/shm/opensbi-tmp
typeset -r U_BOOT_TMP=/dev/shm/u-boot-tmp
typeset -rx ARCH=riscv64
typeset -rx CROSS_COMPILE=${ARCH}-suse-linux-
typeset -x SRC_DIR=~/git/github/starfive/opensbi
typeset -x PAYLOAD_FILE=${U_BOOT_TMP}/u-boot.bin
typeset -x FDT_FILE=${U_BOOT_TMP}/u-boot.dtb
typeset BOARD COPY DEBUG OPTS

# Get options
while getopts "b:cds:h" ARG; do
  case ${ARG} in
    b) BOARD=${OPTARG}
       ;;
    c) COPY=1
       ;;
    d) DEBUG=1
       ;;
    s) SRC_DIR=${OPTARG}
       ;;
    h|*) usage
       ;;
  esac
done
shift $((OPTIND-1))

# Board model must be filled!
[[ -z "${BOARD}" ]] \
  && error "Board model must be filled!"

# Define specific options if needed
case ${BOARD} in
  beaglev|starlight|visionfive|visionfive2-sdk)
    OPTS="FW_PAYLOAD_PATH=${PAYLOAD_FILE} FW_FDT_PATH=${FDT_FILE}"
    ;;
  visionfive2)
    #OPTS="FW_TEXT_START=0x40000000"
    unset COPY
    ;;
esac

# Extract git branch if provided
if [[ "${SRC_DIR#*:}" != "${SRC_DIR}" ]]; then
  SRC_BRANCH=${SRC_DIR#*:}
  SRC_DIR=${SRC_DIR%:*}
fi

# Remove old TMPFS and re-create it
echo "- Cleaning/Creating ${TMPFS} directory..."
rm -rf ${TMPFS} \
  || error "Cannot clean temporary directory ${TMPFS}!"
mkdir -p ${TMPFS} \
  || error "Cannot create temporary directory ${TMPFS}!"

# Copy source in the tmpfs directory
rsync -aq ${SRC_DIR}/ ${TMPFS} \
  || error "Cannot copy ${SRC_DIR}/* in ${TMPFS}!"

# Go to build directory
cd ${TMPFS}

# Change branch if needed
if [[ -n "${SRC_BRANCH}" ]]; then
  echo "- Checking out branch ${SRC_BRANCH}..."
  git checkout ${SRC_BRANCH}
fi

# Cleanup build
echo "- Cleaning build directory..."
make clean && make distclean

# Compile OpenSBI
echo "- Compiling OpenSBI..."
make PLATFORM=generic DEBUG=${DEBUG} ${OPTS} \
  || error "Failed to compile OpenSBI!"

# Copy firmware file(s) locally if asked
if (( COPY )); then
  for FILE in ${PAYLOAD_FILE} ${FDT_FILE}; do
    copy ${FILE} ${OLDPWD}
  done
fi

# We need to go back into original directory
cd ${OLDPWD}

# Clean exit
exit 0
