#!/bin/sh

# Usage function
function usage() {
cat >&2 <<EOF
${SH_FILE} is used to compile official ATF firmware

Usage: ${SH_FILE} -b board [-h] [-d dir]

Where:
  -b	name of the board to configure (for example: sun50i_a64) 
  -d    compile firmware in debug mode
  -s	ATF source directory
  -h    this help page
EOF
  exit 0
}

# Error function
function error() {
  echo -e "$@" >&2
  exit 1
}

# Copy/Check function
function copy() {
  typeset -r FILE=$1
  typeset -r DEST=$2

  cp ${FILE} ${DEST} >/dev/null 2>&1 \
    || error "Error while copying file ${FILE} to ${DEST}!"
}

# Variable(s)
typeset -r SH_FILE=${0##*/}
typeset -r TMPFS=/dev/shm/atf-tmp
typeset -rx ARCH=arm
typeset -rx CROSS_COMPILE=aarch64-elf-
typeset -x ATF_DIR=~/git/github/arm-trusted-firmware
typeset -x PATH=~/cross-compile/aarch64/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-elf/bin:$PATH
typeset DEBUG=0
typeset RELEASE=release
typeset BOARD

# Get options
while getopts "b:ds:h" ARG; do
  case ${ARG} in
    b) BOARD=${OPTARG}
       ;;
    d) DEBUG=1
       RELEASE=debug
       ;;
    s) ATF_DIR=${OPTARG}
       ;;
    h|*) usage
       ;;
  esac
done
shift $((OPTIND-1))

# Board model must be filled!
[[ -z "${BOARD}" ]] \
  && error "Board model must be filled!\n"

# Remove old TMPFS and re-create it
echo "- Cleaning/Creating ${TMPFS} directory..."
rm -rf ${TMPFS} \
  || error "Cannot clean temporary directory ${TMPFS}!"
mkdir -p ${TMPFS} \
  || error "Cannot create temporary directory ${TMPFS}!"

# Copy ATF source in the tmpfs directory
#rsync -aq --exclude=.git ${ATF_DIR}/ ${TMPFS} \
rsync -aq ${ATF_DIR}/ ${TMPFS} \
  || error "Cannot copy ${ATF_DIR}/* in ${TMPFS}!"

# Cleanup ATF build
echo "- Cleaning ATF build directory..."
cd ${TMPFS}
make clean && make distclean

# Compile ATF
echo "- Compiling ATF for ${BOARD} board..."
make PLAT=${BOARD} DEBUG=${DEBUG} bl31 \
  || error "Failed to compile ATF!"

# Copy compiled bl31.bin
echo "- Copying BL31 (ATF firmware) file..."
copy build/${BOARD}/${RELEASE}/bl31.bin ${OLDPWD}/atf-bl31.bin

# We need to go back into original directory
cd ${OLDPWD}

# Clean exit
exit 0
