#!/bin/sh

# Usage function
function usage() {
cat >&2 <<EOF
${SH_FILE} is used to compile official U-Boot binary for AmLogic s905x SoC based board

Usage: ${SH_FILE} -b board [-h]

Where:
  -b	name of the board configure (for example: khadas-vim) 
  -h    this help page
EOF
  exit 1
}

# Variable(s)
typeset -r SH_FILE=${0##*/}
typeset -rx U_BOOT_DIR=~/git/github/u-boot
typeset -rx ARCH=arm
typeset -rx CROSS_COMPILE=aarch64-elf-
typeset -x PATH=~/cross-compile/aarch64/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-elf/bin:$PATH
typeset BOARD

# Get options
while getopts "b:h" ARG; do
  case ${ARG} in
    b) BOARD=${OPTARG}
       ;;
    h|*) usage
       ;;
  esac
done
shift $((OPTIND-1))

# Board model must be filled!
[[ -z "${BOARD}" ]]                              \
  && echo -e "Board model must be filled!\n" >&2 \
  && usage

# Cleanup U-Boot build
echo "- Cleaning U-Boot build directory..."
cd ${U_BOOT_DIR}
make clean && make mrproper && make distclean

# Configure U-Boot
echo "- Configure U-Boot for ${BOARD} board..."
make ${BOARD}_defconfig

# Compile U-Boot
echo "- Compiling U-Boot..."
make || echo "Failed to compile U-Boot!" >&2

# We need to go back into original directory
cd ${OLDPWD}

# Clean exit
exit 0
