#!/bin/sh

# Usage function
function usage() {
cat >&2 <<EOF
${SH_FILE} is used to compile, generate and burn official U-Boot for Amlogic GXL/GXM SoC

Usage: ${SH_FILE} [a-] -b board

Where:
  -a    use official ARM ATF fimrware
  -b    name of the board to configure

Currently supported Amlogic boards are: khadas-vim, khadas-vim2, libretech-cc
EOF
  exit 0
}

# Error function
function error() {
  echo -e "$@" >&2
  exit 1
}

# Variable(s)
typeset -r SH_FILE=${0##*/}
typeset -i ATF_FW=0
typeset -i USE_GXLIMG=0
typeset GENERATE_OPTS="-c -s"
typeset AMLOGIC_U_BOOT_DIR
typeset AMLOGIC_U_BOOT_BOARD
typeset ATF_FW_BOARD
typeset BOARD

# Get options
while getopts "ab:gh" ARG; do
  case ${ARG} in
    a) ATF_FW=1
       ;;
    b) BOARD=${OPTARG}
       ;;
    g) USE_GXLIMG=1
       ;;
    h|*) usage
       ;;
  esac
done
shift $((OPTIND-1))

# Board model must be filled!
[[ -z "${BOARD}" ]] \
  && error "Board model must be filled!"

case ${BOARD} in
  khadas-vim)
    AMLOGIC_U_BOOT_DIR=~/git/github/u-boot-amlogic
    AMLOGIC_U_BOOT_BOARD="kvim"
    ATF_FW_BOARD="gxl"
    ;;
  khadas-vim2)
    AMLOGIC_U_BOOT_DIR=~/git/github/u-boot-amlogic
    AMLOGIC_U_BOOT_BOARD="kvim2"
    ATF_FW_BOARD="gxl"
    ;;
  libretech-cc)
    AMLOGIC_U_BOOT_DIR=~/git/github/u-boot-amlogic-libretech-cc
    AMLOGIC_U_BOOT_BOARD="libretech_cc"
    ATF_FW_BOARD="gxl"
    ;;
esac

# Compile official ARM Trusted Firmware if needed
if (( ATF_FW )); then
  GENERATE_OPTS+=" -a"
  compile_mainline_atf -b ${ATF_FW_BOARD}
fi

# Use GXLIMG?
(( USE_GXLIMG )) && GENERATE_OPTS+=" -g"

# Compile official U-Boot for Amlogic based board and burn it on /dev/mmcblk0
compile_mainline_u-boot -b ${BOARD} \
  && generate_gxl_gxm_bootloader -u ${AMLOGIC_U_BOOT_DIR} -b ${AMLOGIC_U_BOOT_BOARD} ${GENERATE_OPTS}

exit $?
