#!/bin/sh

# Compile official U-Boot for Libretech ALL-H3-CC board and burn it on /dev/mmcblk0
compile_mainline_atf -b rk3328 \
  && compile_mainline_u-boot -b evb-rk3328 -s ~/git/github/u-boot-rockchip \
  && rk_bootloader

exit $?
