#!/bin/sh

# Compile official U-Boot for Libretech ALL-H3-CC board and burn it on /dev/mmcblk0
compile_mainline_atf -b sun50i_a64                              \
  && compile_mainline_u-boot -a arm64 -b libretech_all_h3_cc_h5 \
  && sunxi_bootloader -c -s

exit $?
